Update QR code Library from qrcode to pyQRCode
lavaloon-eg/ksa_compliance pull request #27
Opened 2024-05-20 06:57 UTC by mostafaradwann

2024-05-20 09:02 UTC, mhaggag requested changes

2024-05-20 09:02 UTC, mhaggag commented on ksa_compliance/ksa_compliance/doctype/sales_invoice_additional_fields/sales_invoice_additional_fields.py
> +            return "No QR Code"
How is the virtual field intended to be used? If the caller embeds its result directly into an `<img>` element, it won't work when it says "No QR Code". We have a couple of options:
* Return `None` when there's no QR code. The caller has to check for truthiness before embedding in an image (i.e. `if doc.qr_code: do_something`)
* Always return an image, but use a special image to indicate no QR code (e.g. load from assets or render an SVG)

I think the first option's easier, especially if we're going to just embed them in print formats.

2024-05-20 09:02 UTC, mhaggag commented
Also, please add the package to `pyproject.toml`. We don't control frappe dependencies, so they can potentially replace the library with something else and break our code if we don't add the dependency ourselves.

2024-05-20 10:12 UTC, mostafaradwann commented on ksa_compliance/ksa_compliance/doctype/sales_invoice_additional_fields/sales_invoice_additional_fields.py
> +            buffer = BytesIO()
done

2024-05-20 19:13 UTC, mhaggag approved these changes

2024-05-20 19:13 UTC, mhaggag commented on ksa_compliance/ksa_compliance/doctype/sales_invoice_additional_fields/sales_invoice_additional_fields.py
> +                img_str = base64.b64encode(buffer.getvalue()).decode("utf-8")
Please keep the return statement in the with block (indent)

2024-05-20 19:13 UTC, mhaggag commented on ksa_compliance/ksa_compliance/doctype/sales_invoice_additional_fields/sales_invoice_additional_fields.py
> +            return None
We can now invert the if and exit early (i.e. `if not self.qr_code:` and exit the function to unindent the rest)

2024-05-21 11:45 UTC, mhaggag commented
The print format changes were included by mistake. Please do an interactive rebase and remove them.

2024-05-21 13:38 UTC, merged